### ISSUE TITLE
Unable to launch VM..  vcenter context deadline exceeded

### ISSUE THREAD

**Issue by alexnaris** [Fred78290/kubernetes-vmware-autoscaler#13]
Hello,

I am having issues with this version of autoscaler.  The autoscaled vm is cloned fine in vcenter, however, autoscaler app appears to lose track of it and fails with the following errors:

`time="2021-11-22T19:49:20Z" level=info msg="Launch VM:vmware-ca-k8s-autoscaled-01 for nodegroup: vmware-ca-k8s"
time="2021-11-22T19:49:20Z" level=info msg="Launch VM:vmware-ca-k8s-autoscaled-02 for nodegroup: vmware-ca-k8s"
time="2021-11-22T19:56:04Z" level=error msg="Unable to launch VM:vmware-ca-k8s-autoscaled-02 for nodegroup: vmware-ca-k8s. Reason: could not start VM: vmware-ca-k8s-autoscaled-02, reason: Post \"https://vcenter/sdk\": context deadline exceeded"
time="2021-11-22T19:56:04Z" level=error msg="unable to launch the VM owned by node: vmware-ca-k8s-autoscaled-02, reason: could not start VM: vmware-ca-k8s-autoscaled-02, reason: Post \"https://vcenter/sdk\": context deadline exceeded"
time="2021-11-22T19:56:04Z" level=error msg="Unable to launch VM:vmware-ca-k8s-autoscaled-01 for nodegroup: vmware-ca-k8s. Reason: could not start VM: vmware-ca-k8s-autoscaled-01, reason: Post \"https://vcenter/sdk\": context deadline exceeded"`

**Comment by Fred78290** [comment]
Hello it's look like that the pod could not resolve the name vcenter.
The reason is that coredns could not resolve the dns name vcenter because it will try to resolve it as internal name in the domain cluster.local.
To solve the problem, use a full qualified domain name for vcenter or use IP.

You can change it by editing config map config-cluster-autoscaler in namespace kube-system

Regards
